services:
  backend:
    build:
      context: ./backend
      dockerfile: SignalR.Api/Dockerfile
    ports:
      - "7250:8080"
      - "7251:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - signalr-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - signalr-network

networks:
  signalr-network:
    driver: bridge
